name: amp8
recipe: drupal8
config:
  php: '7.2'
  xdebug: true
env_file:
  - .env
services:
  appserver:
    webroot: web
    type: php
    run:
      - bash /app/scripts/lando/run.sh
  database:
    type: mariadb
events:
  post-start:
    - bash /app/scripts/lando/post-start.sh
  post-db-import:
    - appserver: /app/vendor/bin/drush updb --root=/app/web -y
    - appserver: /app/vendor/bin/drush cim --root=/app/web -y
    - appserver: /app/vendor/bin/drush cr --root=/app/web
    - appserver: /app/vendor/bin/drush upwd admin password --root=/app/web
    - appserver: echo "Run composer install when first installed or modules are updated"
    - appserver: echo "Log in with credentials admin/password"
tooling:
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit --group schema_metatag"
    cmd: "/app/vendor/bin/phpunit --configuration /app/web/core --printer=\\Drupal\\Tests\\Listeners\\HtmlOutputPrinter"
  phpunit-prepare:
    service: appserver
    description: "One time update so tests will run in php 7.2"
    cmd: composer run-script drupal-phpunit-upgrade
  updatecore:
    service: appserver
    description: "Update core with 'composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies'"
    cmd: echo "Update core with 'composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies'"
