name: amp8
recipe: drupal8
config:
  webroot: web
  php: '7.2'
  drush: composer
  index: false
  edge: false
  cache: false
  xdebug: true
env_file:
  - .env
services:
  appserver:
    config:
      conf: config/php.ini
    via: apache
    run:
      - bash /app/scripts/lando/run.sh
  database:
    type: mariadb
events:
  post-start:
    - bash /app/scripts/lando/post-start.sh
  post-db-import:
    - bash /app/scripts/lando/post-db.sh
tooling:
  drush:
    cmd: /app/vendor/bin/drush --root=/app/web
  phpunit:
    service: appserver
    description: "Run PHP Unit tests: lando phpunit --group schema_metatag"
    cmd: '/app/vendor/bin/phpunit --configuration /app/web/core/ --printer=\\Drupal\\Tests\\Listeners\\HtmlOutputPrinter'
  phpunit-prepare:
    service: appserver
    description: "One time update so tests will run in php 7.2"
    cmd: composer run-script drupal-phpunit-upgrade
  updatecore:
    service: appserver
    description: "Update core with 'composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies'"
    cmd: echo "Update core with 'composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies'"
